package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mxschmitt/playwright-go"
	"github.com/zajuna-app/core/internal/capture"
	"github.com/zajuna-app/core/internal/storage/sqlite"
	"github.com/zajuna-app/core/internal/zajuna"
)

var visualBaselines = map[string]string{
	// Filled from deterministic screenshots generated by the same bundled
	// Chromium runtime. Update deliberately when the design changes.
	"desktop": "db65556853c8046894bc4f57b1fbfbb6892ab0ee5f2cfbb5fb277bf5db61996c",
	"tablet":  "7d0e1158d0c52e4da6d601080a617155ce9171ffa905357b72061eedde576f5b",
	"mobile":  "908a31050fea8ce2ac2738fc332c0d8c6b0e154391b8aab96931df02f8e41d89",
}

func TestDashboardBrowserSmoke(t *testing.T) {
	if os.Getenv("ZAJUNA_RUN_BROWSER_SMOKE") != "1" {
		t.Skip("browser smoke disabled")
	}

	dataDir := t.TempDir()
	store, err := sqlite.Open(dataDir)
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	if err := writeConfig(dataDir, appConfig{SetupComplete: true, ZajunaUsername: "qa-user", CredentialsStored: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := store.UpsertFichas(context.Background(), []zajuna.Ficha{{ExternalID: "qa-ficha", Name: "Ficha de prueba", CourseID: "qa-course"}}); err != nil {
		t.Fatal(err)
	}
	// Keep date labels stable so the pixel baseline only changes when the UI
	// changes, not on every test run.
	if _, err := store.DB().Exec(`UPDATE fichas SET synced_at = ?, updated_at = ?`, "2026-01-01T12:00:00Z", "2026-01-01T12:00:00Z"); err != nil {
		t.Fatal(err)
	}

	server := httptest.NewServer(newRouterWithServices(dataDir, &memoryCredentialStore{}, nil, store, nil))
	defer server.Close()

	runtime := capture.Resolve("")
	pw, err := runtime.Start()
	if err != nil {
		t.Fatal(err)
	}
	defer pw.Stop()
	browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Headless: playwright.Bool(true),
		// Keep screenshot rasterization stable across repeated local runs. The
		// production Chromium path is intentionally unchanged.
		Args: []string{"--disable-gpu", "--disable-lcd-text", "--font-render-hinting=none"},
	})
	if err != nil {
		t.Fatal(err)
	}
	defer browser.Close()
	browserContext, err := browser.NewContext()
	if err != nil {
		t.Fatal(err)
	}
	defer browserContext.Close()
	page, err := browserContext.NewPage()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := page.Goto(server.URL + "/"); err != nil {
		t.Fatal(err)
	}
	if err := page.Locator("#dashboard-main").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("dashboard did not become visible: %v", err)
	}
	// The shell paints first; the overview arrives with its data and page chunk.
	if err := page.Locator("#overview-jobs").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("overview did not render: %v", err)
	}

	title, err := page.Title()
	if err != nil || title != "Zajuna App · Operación local" {
		t.Fatalf("unexpected page title %q: %v", title, err)
	}
	// "/" redirects to /resumen; the accessible heading names the current page.
	pageTitle, err := page.Locator("#dashboard-title").TextContent()
	if err != nil || strings.TrimSpace(pageTitle) != "Resumen" {
		t.Fatalf("unexpected dashboard title %q: %v", pageTitle, err)
	}
	for _, selector := range []string{"main[aria-labelledby='dashboard-title']", "#workspace", "#overview-jobs", "#ficha-select", ".evidence-gallery", ".reports-card"} {
		count, err := page.Locator(selector).Count()
		if err != nil || count != 1 {
			t.Fatalf("selector %s count = %d, err = %v", selector, count, err)
		}
	}

	output := filepath.Join(t.TempDir(), "dashboard.png")
	if _, err := page.Screenshot(playwright.PageScreenshotOptions{Path: playwright.String(output), FullPage: playwright.Bool(true)}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(output); err != nil {
		t.Fatal(err)
	}

	for _, viewport := range []struct {
		name   string
		width  int
		height int
	}{
		{name: "desktop", width: 1440, height: 900},
		{name: "tablet", width: 1024, height: 900},
		{name: "mobile", width: 390, height: 844},
	} {
		if err := page.SetViewportSize(viewport.width, viewport.height); err != nil {
			t.Fatalf("set %s viewport: %v", viewport.name, err)
		}
		if _, err := page.Goto(server.URL + "/resumen"); err != nil {
			t.Fatalf("navigate %s viewport: %v", viewport.name, err)
		}
		if _, err := page.AddStyleTag(playwright.PageAddStyleTagOptions{Content: playwright.String(`*,*::before,*::after { animation:none !important; transition:none !important; caret-color:transparent !important; }`)}); err != nil {
			t.Fatalf("freeze motion at %s viewport: %v", viewport.name, err)
		}
		if _, err := page.Evaluate(`async () => {
			await document.fonts.ready;
			await Promise.all([
				document.fonts.load('650 13px Inter'),
				document.fonts.load('700 27px "Plus Jakarta Sans"'),
				document.fonts.load('600 9px "IBM Plex Mono"'),
			]);
			return true;
		}`); err != nil {
			t.Fatalf("wait fonts at %s viewport: %v", viewport.name, err)
		}
		page.WaitForTimeout(500)
		if err := page.Locator("#workspace").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
			t.Fatalf("workspace did not become visible at %s viewport: %v", viewport.name, err)
		}
		if err := page.Locator("#overview-jobs").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
			t.Fatalf("overview did not render at %s viewport: %v", viewport.name, err)
		}
		overflow, err := page.Evaluate(`() => document.documentElement.scrollWidth <= window.innerWidth + 1`)
		if err != nil {
			t.Fatalf("measure %s viewport: %v", viewport.name, err)
		}
		if visible, ok := overflow.(bool); !ok || !visible {
			t.Fatalf("%s viewport has unexpected horizontal overflow: %#v", viewport.name, overflow)
		}
		unnamed, err := page.Evaluate(`() => Array.from(document.querySelectorAll('button,a,input,select,textarea')).filter((element) => {
			if (element.getAttribute('aria-hidden') === 'true' || element.disabled) return false
			const label = element.getAttribute('aria-label') || element.getAttribute('title') || element.textContent?.trim()
			if (label) return false
			if (element.id && document.querySelector('label[for="' + CSS.escape(element.id) + '"]')) return false
			return !element.closest('label')
		}).map((element) => ({tag: element.tagName, id: element.id, text: element.textContent?.trim()}))`)
		if err != nil {
			t.Fatalf("inspect accessible names at %s viewport: %v", viewport.name, err)
		}
		if values, ok := unnamed.([]any); !ok || len(values) > 0 {
			t.Fatalf("unnamed interactive elements at %s viewport: %#v", viewport.name, unnamed)
		}
		if viewport.width <= 720 {
			visible, err := page.Locator(".sidebar").IsVisible()
			if err != nil || visible {
				t.Fatalf("sidebar should collapse on mobile: visible=%v err=%v", visible, err)
			}
		}
		if viewport.width > 980 {
			// The navigation and the overview side panel follow the scroll.
			// Assert it functionally: the full-page capture below renders them
			// static because sticky layers make it nondeterministic.
			followed, err := page.Evaluate(`async () => {
				window.scrollTo(0, document.documentElement.scrollHeight)
				await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)))
				const inView = (selector) => {
					const box = document.querySelector(selector).getBoundingClientRect()
					// 1px slack: the last scroll position is rounded.
					return box.top >= -1 && box.top < window.innerHeight && box.bottom > 0
				}
				const result = window.scrollY > 0 && inView('.sidebar') && inView('.overview-side')
				window.scrollTo(0, 0)
				return result
			}`)
			if err != nil {
				t.Fatalf("measure sticky panels at %s viewport: %v", viewport.name, err)
			}
			if ok, _ := followed.(bool); !ok {
				t.Fatalf("sidebar and overview panel should stay in view while scrolling at %s viewport", viewport.name)
			}
		}
		selectedFicha, err := page.Locator("#ficha-select").InputValue()
		if err != nil || selectedFicha == "" {
			t.Fatalf("unexpected selected ficha at %s viewport: %q (err=%v)", viewport.name, selectedFicha, err)
		}
		responsiveOutput := filepath.Join(t.TempDir(), viewport.name+".png")
		if artifactDir := os.Getenv("ZAJUNA_VISUAL_ARTIFACT_DIR"); artifactDir != "" {
			if err := os.MkdirAll(artifactDir, 0o700); err != nil {
				t.Fatalf("create visual artifact directory: %v", err)
			}
			responsiveOutput = filepath.Join(artifactDir, viewport.name+".png")
		}
		if _, err := page.Screenshot(playwright.PageScreenshotOptions{
			Path:     playwright.String(responsiveOutput),
			FullPage: playwright.Bool(true),
			// Native select text is rasterized by the host widget and can differ
			// by a few pixels between identical Chromium runs. Keep the control
			// geometry in the visual baseline while asserting its value below.
			// Sticky panels have no single position in a full-page capture and
			// their layers antialias differently between runs; they are
			// captured static and their scroll behavior is asserted above.
			Style: playwright.String(`.ficha-control { color: transparent !important; } .sidebar, .overview-side { position: static !important; height: auto !important; max-height: none !important; overflow: visible !important; }`),
		}); err != nil {
			t.Fatalf("capture %s viewport: %v", viewport.name, err)
		}
		if _, err := os.Stat(responsiveOutput); err != nil {
			t.Fatalf("missing %s visual artifact: %v", viewport.name, err)
		}
		contents, err := os.ReadFile(responsiveOutput)
		if err != nil {
			t.Fatalf("read %s visual artifact: %v", viewport.name, err)
		}
		hash := sha256.Sum256(contents)
		actualHash := hex.EncodeToString(hash[:])
		t.Logf("visual baseline %s sha256=%s", viewport.name, actualHash)
		if expected := visualBaselines[viewport.name]; expected != "" && actualHash != expected {
			t.Fatalf("visual baseline mismatch for %s: got %s want %s", viewport.name, actualHash, expected)
		}
	}

	// Between 721 and 980 px only the navigation is sticky (the overview
	// columns stack), a range the baseline viewports above do not cover.
	if err := page.SetViewportSize(820, 700); err != nil {
		t.Fatalf("set narrow tablet viewport: %v", err)
	}
	if _, err := page.Goto(server.URL + "/resumen"); err != nil {
		t.Fatalf("navigate narrow tablet viewport: %v", err)
	}
	if err := page.Locator("#overview-jobs").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("overview did not render at narrow tablet viewport: %v", err)
	}
	sidebarFollows, err := page.Evaluate(`async () => {
		window.scrollTo(0, document.documentElement.scrollHeight)
		await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)))
		const box = document.querySelector('.sidebar').getBoundingClientRect()
		return window.scrollY > 0 && box.top >= -1 && box.top < 1
	}`)
	if err != nil {
		t.Fatalf("measure sticky sidebar at narrow tablet viewport: %v", err)
	}
	if ok, _ := sidebarFollows.(bool); !ok {
		t.Fatal("sidebar should stay pinned to the top while scrolling at 820px")
	}
}

func TestWCAGKeyboardMatrix(t *testing.T) {
	if os.Getenv("ZAJUNA_RUN_BROWSER_SMOKE") != "1" {
		t.Skip("browser smoke disabled")
	}

	dataDir := t.TempDir()
	store, err := sqlite.Open(dataDir)
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	if err := writeConfig(dataDir, appConfig{SetupComplete: true, ZajunaUsername: "qa-user", CredentialsStored: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := store.UpsertFichas(context.Background(), []zajuna.Ficha{{ExternalID: "qa-ficha", Name: "Ficha de prueba", CourseID: "qa-course"}}); err != nil {
		t.Fatal(err)
	}

	server := httptest.NewServer(newRouterWithServices(dataDir, &memoryCredentialStore{}, nil, store, nil))
	defer server.Close()

	runtime := capture.Resolve("")
	pw, err := runtime.Start()
	if err != nil {
		t.Fatal(err)
	}
	defer pw.Stop()
	browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Headless: playwright.Bool(true),
		Args:     []string{"--disable-gpu", "--disable-lcd-text", "--font-render-hinting=none"},
	})
	if err != nil {
		t.Fatal(err)
	}
	defer browser.Close()
	browserContext, err := browser.NewContext()
	if err != nil {
		t.Fatal(err)
	}
	defer browserContext.Close()
	page, err := browserContext.NewPage()
	if err != nil {
		t.Fatal(err)
	}

	routes := []string{
		"/resumen",
		"/fichas",
		"/checklist",
		"/actividades",
		"/evidencias",
		"/trabajos",
		"/reportes",
		"/configuracion",
		"/diagnostico",
		"/notificaciones",
	}

	for _, route := range routes {
		if err := page.SetViewportSize(1366, 768); err != nil {
			t.Fatalf("%s laptop viewport: %v", route, err)
		}
		if _, err := page.Goto(server.URL + route); err != nil {
			t.Fatalf("navigate %s: %v", route, err)
		}
		if err := page.Locator("#dashboard-main").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
			t.Fatalf("%s main landmark: %v", route, err)
		}

		skipCount, err := page.Locator("a.skip-link[href='#dashboard-main']").Count()
		if err != nil || skipCount != 1 {
			t.Fatalf("%s missing skip link: count=%d err=%v", route, skipCount, err)
		}
		liveCount, err := page.Locator(".toast-region[aria-live='polite']").Count()
		if err != nil || liveCount != 1 {
			t.Fatalf("%s missing toast live region: count=%d err=%v", route, liveCount, err)
		}

		if _, err := page.Evaluate(`() => document.body.focus()`); err != nil {
			t.Fatalf("%s blur: %v", route, err)
		}
		if err := page.Keyboard().Press("Tab"); err != nil {
			t.Fatalf("%s Tab: %v", route, err)
		}
		firstFocus, err := page.Evaluate(`() => {
			const el = document.activeElement
			return { tag: el?.tagName, className: el?.className, href: el?.getAttribute?.('href'), text: el?.textContent?.trim() }
		}`)
		if err != nil {
			t.Fatalf("%s first focus: %v", route, err)
		}
		focusMap, _ := firstFocus.(map[string]any)
		if fmt.Sprint(focusMap["className"]) != "skip-link" || fmt.Sprint(focusMap["href"]) != "#dashboard-main" {
			t.Fatalf("%s first Tab did not land on skip link: %#v", route, firstFocus)
		}
		if err := page.Keyboard().Press("Enter"); err != nil {
			t.Fatalf("%s skip Enter: %v", route, err)
		}
		afterSkip, err := page.Evaluate(`() => document.activeElement?.id`)
		if err != nil || fmt.Sprint(afterSkip) != "dashboard-main" {
			t.Fatalf("%s skip link did not move focus to main: %#v err=%v", route, afterSkip, err)
		}

		landmarks, err := page.Evaluate(`() => ({
			nav: document.querySelectorAll('nav, [aria-label="Navegación principal"]').length,
			main: document.querySelectorAll('main').length,
			h1: document.querySelectorAll('h1').length,
		})`)
		if err != nil {
			t.Fatalf("%s landmarks: %v", route, err)
		}
		lm, _ := landmarks.(map[string]any)
		if toInt(lm["main"]) != 1 || toInt(lm["h1"]) != 1 {
			t.Fatalf("%s expected 1 main and 1 h1, got %#v", route, landmarks)
		}

		smallPrimary, err := page.Evaluate(`() => Array.from(document.querySelectorAll('.button, .header-icon, .settings-tab, a.skip-link, input:not([type="checkbox"]):not([type="radio"]), select, textarea')).filter((el) => {
			const r = el.getBoundingClientRect()
			if (r.width === 0 || r.height === 0) return false
			return r.width < 44 || r.height < 44
		}).map((el) => ({ tag: el.tagName, className: el.className, w: Math.round(el.getBoundingClientRect().width), h: Math.round(el.getBoundingClientRect().height), text: el.textContent?.trim()?.slice(0, 40) }))`)
		if err != nil {
			t.Fatalf("%s target size: %v", route, err)
		}
		if values, ok := smallPrimary.([]any); ok && len(values) > 0 {
			t.Fatalf("%s primary controls below 44px: %#v", route, smallPrimary)
		}

		if err := page.SetViewportSize(320, 900); err != nil {
			t.Fatalf("%s 320 viewport: %v", route, err)
		}
		page.WaitForTimeout(200)
		overflow320, err := page.Evaluate(`() => {
			const extra = Array.from(document.querySelectorAll('body *')).map((el) => {
				const r = el.getBoundingClientRect()
				return { tag: el.tagName, className: String(el.className).slice(0, 80), right: Math.round(r.right), w: Math.round(r.width) }
			}).filter((item) => item.right > window.innerWidth).sort((a, b) => b.right - a.right).slice(0, 8)
			return {
				ok: document.documentElement.scrollWidth <= window.innerWidth + 1,
				scrollWidth: document.documentElement.scrollWidth,
				innerWidth: window.innerWidth,
				extra,
			}
		}`)
		if err != nil {
			t.Fatalf("%s 320 overflow: %v", route, err)
		}
		overflowMap, _ := overflow320.(map[string]any)
		if overflowMap["ok"] != true {
			t.Fatalf("%s horizontal overflow at 320 CSS px: %#v", route, overflow320)
		}

		for _, scalePercent := range []int{125, 150, 200} {
			effectiveWidth := 1366 * 100 / scalePercent
			effectiveHeight := 768 * 100 / scalePercent
			if err := page.SetViewportSize(effectiveWidth, effectiveHeight); err != nil {
				t.Fatalf("%s effective viewport at %d%% scale: %v", route, scalePercent, err)
			}
			page.WaitForTimeout(150)
			scaleState, err := page.Evaluate(`() => ({
				mainVisible: !!document.getElementById('dashboard-main') && document.getElementById('dashboard-main').getClientRects().length > 0,
				skipPresent: !!document.querySelector('a.skip-link'),
				noDocumentOverflow: document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1,
			})`)
			if err != nil {
				t.Fatalf("%s effective viewport at %d%% scale inspect: %v", route, scalePercent, err)
			}
			scaleMap, _ := scaleState.(map[string]any)
			if scaleMap["mainVisible"] != true || scaleMap["skipPresent"] != true || scaleMap["noDocumentOverflow"] != true {
				t.Fatalf("%s unusable at effective %d%% scale viewport: %#v", route, scalePercent, scaleState)
			}
		}

		if err := page.SetViewportSize(1366, 768); err != nil {
			t.Fatalf("%s restore viewport for zoom: %v", route, err)
		}
		if _, err := page.Evaluate(`() => { document.documentElement.style.zoom = '200%'; return true }`); err != nil {
			t.Fatalf("%s zoom: %v", route, err)
		}
		page.WaitForTimeout(150)
		zoomState, err := page.Evaluate(`() => ({
			mainVisible: !!document.getElementById('dashboard-main') && document.getElementById('dashboard-main').getClientRects().length > 0,
			skipPresent: !!document.querySelector('a.skip-link'),
		})`)
		if _, resetErr := page.Evaluate(`() => { document.documentElement.style.zoom = ''; return true }`); resetErr != nil {
			t.Fatalf("%s reset zoom: %v", route, resetErr)
		}
		if err != nil {
			t.Fatalf("%s zoom inspect: %v", route, err)
		}
		zoomMap, _ := zoomState.(map[string]any)
		if zoomMap["mainVisible"] != true || zoomMap["skipPresent"] != true {
			t.Fatalf("%s unusable at 200%% zoom: %#v", route, zoomState)
		}

		t.Logf("keyboard/reflow pass %s skip=ok live=ok h1=1 overflow320=ok scale-viewports=125/150/200 zoom200=ok", route)
	}

	if err := page.SetViewportSize(1366, 768); err != nil {
		t.Fatalf("restore laptop viewport: %v", err)
	}
	if _, err := page.Goto(server.URL + "/configuracion"); err != nil {
		t.Fatal(err)
	}
	if err := page.Locator("#settings-tab-account").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("settings tabs: %v", err)
	}
	if err := page.Locator("#settings-tab-account").Focus(); err != nil {
		t.Fatal(err)
	}
	page.WaitForTimeout(100)
	if err := page.Keyboard().Press("ArrowRight"); err != nil {
		t.Fatal(err)
	}
	if err := page.Locator("#settings-tab-capture[aria-selected='true']").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		selected, evalErr := page.Evaluate(`() => document.querySelector('[role="tab"][aria-selected="true"]')?.id`)
		t.Fatalf("settings arrow keys did not move tab: %#v wait=%v eval=%v", selected, err, evalErr)
	}
}

func toInt(value any) int {
	switch typed := value.(type) {
	case int:
		return typed
	case int64:
		return int(typed)
	case float64:
		return int(typed)
	default:
		return -1
	}
}

func TestEvidenciasBrowserSmoke(t *testing.T) {
	if os.Getenv("ZAJUNA_RUN_BROWSER_SMOKE") != "1" {
		t.Skip("browser smoke disabled")
	}

	dataDir := t.TempDir()
	store, err := sqlite.Open(dataDir)
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	if err := writeConfig(dataDir, appConfig{SetupComplete: true, ZajunaUsername: "qa-user", CredentialsStored: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := store.UpsertFichas(context.Background(), []zajuna.Ficha{{ExternalID: "qa-ficha", Name: "Ficha de prueba", CourseID: "qa-course"}}); err != nil {
		t.Fatal(err)
	}

	server := httptest.NewServer(newRouterWithServices(dataDir, &memoryCredentialStore{}, nil, store, nil))
	defer server.Close()

	runtime := capture.Resolve("")
	pw, err := runtime.Start()
	if err != nil {
		t.Fatal(err)
	}
	defer pw.Stop()
	browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Headless: playwright.Bool(true),
		Args:     []string{"--disable-gpu", "--disable-lcd-text", "--font-render-hinting=none"},
	})
	if err != nil {
		t.Fatal(err)
	}
	defer browser.Close()
	browserContext, err := browser.NewContext()
	if err != nil {
		t.Fatal(err)
	}
	defer browserContext.Close()
	page, err := browserContext.NewPage()
	if err != nil {
		t.Fatal(err)
	}

	if _, err := page.Goto(server.URL + "/evidencias"); err != nil {
		t.Fatal(err)
	}
	if err := page.Locator("#dashboard-main").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("evidencias main landmark: %v", err)
	}

	pageTitle, err := page.Locator("#page-title").TextContent()
	if err != nil || pageTitle != "Evidencias" {
		t.Fatalf("unexpected evidencias title %q: %v", pageTitle, err)
	}
	eyebrow, err := page.Locator(".page-head .eyebrow").First().TextContent()
	if err != nil || eyebrow != "Tus evidencias" {
		t.Fatalf("unexpected evidencias eyebrow %q: %v", eyebrow, err)
	}

	activeNav, err := page.Locator(`a.sidebar-item.active[href="/evidencias"]`).Count()
	if err != nil || activeNav != 1 {
		t.Fatalf("evidencias nav not active: count=%d err=%v", activeNav, err)
	}

	for _, selector := range []string{".evidence-gallery", "#evidence-group-search", "#evidence-group-filter", ".gallery-summary"} {
		if err := page.Locator(selector).First().WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
			t.Fatalf("evidencias missing %s: %v", selector, err)
		}
	}

	emptyOrGrid, err := page.Evaluate(`() => {
		const empty = document.querySelector('.evidence-gallery .empty')
		const grid = document.querySelector('.evidence-gallery-grid')
		return {
			hasEmpty: !!empty,
			emptyText: empty?.textContent?.trim() || '',
			hasGrid: !!grid,
		}
	}`)
	if err != nil {
		t.Fatalf("inspect evidencias gallery: %v", err)
	}
	gallery, _ := emptyOrGrid.(map[string]any)
	if gallery["hasGrid"] != true {
		t.Fatalf("evidencias gallery grid missing: %#v", emptyOrGrid)
	}
	if gallery["hasEmpty"] == true {
		text := fmt.Sprint(gallery["emptyText"])
		if text != "Todavía no hay evidencias en esta ficha." && text != "No encontramos grupos con esos filtros." {
			t.Fatalf("unexpected empty gallery copy: %q", text)
		}
	}

	// Configuración → Almacenamiento: ruta de borrado visible sin credenciales reales.
	// El confirm del navegador se descarta automáticamente sin listener OnDialog.
	if _, err := page.Goto(server.URL + "/configuracion?tab=storage"); err != nil {
		t.Fatal(err)
	}
	if err := page.Locator("#settings-panel-storage").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("settings storage panel: %v", err)
	}
	clearButton := page.Locator(`button:has-text("Borrar evidencias")`)
	if err := clearButton.WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("clear evidences control: %v", err)
	}
	dialogSeen := false
	page.OnDialog(func(dialog playwright.Dialog) {
		dialogSeen = true
		message := dialog.Message()
		if message != "¿Borrar todas las evidencias guardadas en este equipo? Esta acción no se puede deshacer." {
			t.Errorf("unexpected clear dialog: %q", message)
		}
		if err := dialog.Dismiss(); err != nil {
			t.Errorf("dismiss clear dialog: %v", err)
		}
	})
	if err := clearButton.Click(); err != nil {
		t.Fatalf("click clear evidences: %v", err)
	}
	page.WaitForTimeout(200)
	if !dialogSeen {
		t.Fatal("expected clear-evidences confirm dialog")
	}
	label, err := clearButton.TextContent()
	if err != nil || label != "Borrar evidencias" {
		t.Fatalf("clear button should remain idle after dismiss, got %q err=%v", label, err)
	}
	selected, err := page.Locator(`#settings-tab-storage[aria-selected='true']`).Count()
	if err != nil || selected != 1 {
		t.Fatalf("storage tab should stay selected: count=%d err=%v", selected, err)
	}

	t.Log("evidencias smoke: gallery=ok clear-path=ok (confirm dismissed)")
}
